### ISSUE TITLE
Research about google translate API

### ISSUE THREAD

**Issue by arashbahreini** [lingua-games/play-lingua#6]

**Comment by RobertvBraam** [comment]
Nuget package from Google to consume with C# (https://cloud.google.com/translate/docs/reference/libraries/v3/csharp)

**Comment by arashbahreini** [comment]
What if we find an API from google which call from front-end without evolving our backend? 
I mean call a POST API in front-end and send the word to it, then API return pronounce as a bite array or something which would be convertible to playable audio. 
The propose is to pronounce a word (Dutch/Japanese etc)
