### ISSUE TITLE
Find free db cloud and start using it

### ISSUE THREAD

**Issue by arashbahreini** [lingua-games/play-lingua#7]

**Comment by RobertvBraam** [comment]
I think we all have Visual Studio Enterprise. We could use the 150 euro a month free subscription to host our services.

**Comment by arashbahreini** [comment]
Really? How is it possible? 
Is it through Azure? 
Actually Senem found some free/opensource database servers today

**Comment by senemu4** [comment]
![image](https://user-images.githubusercontent.com/39556141/95178204-6cc61180-07bf-11eb-9318-d8a60ed011ec.png)

**Comment by senemu4** [comment]
Yeah we all have enterprise licenses, but they don't belong to us technically 😄

**Comment by arashbahreini** [comment]
We can ask from Nick about it in this way, 
Are we able to temporarily use Azure database for educational propose. 
The fact is that we need a free database just for our tests and design database architecture and models, Then in the next months when our product is something deployable, we will buy some spaces to keep our files/data.
