### ISSUE TITLE
Hosting our Database, Frontend and API service in Docker

### ISSUE THREAD

**Issue by RobertvBraam** [lingua-games/play-lingua#9]
How about hosting all our services in Docker to make it easy to host it locally and in the cloud?

Tasks:
- Build container for each service with CI/CD (maybe using Github Actions?)
- Create Docker Hub with our the containers 
- Docker compose to automate full setup

**Comment by arashbahreini** [comment]
That's a good idea actually. To be honest I was more focusing/thinking about how to implement the movements and games in the front-end. That's why I have not think about CI/CD yet. 
Can you explain more about hosting services in Github actions?
